name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - release
  pull_request:

jobs:
  lint:
    if: '! github.event.pull_request.draft'
    name: Lint code base
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Pre-commit
        env:
          # set the `no-commit-to-branch` to be skipped, otherwise the check fails when we merge to `master` branch
          SKIP: no-commit-to-branch
        uses: pre-commit/action@v3.0.1

  test:
    name: Run tests
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        django_app:
          - authentication
          - notifs
          - subscription
          - core
          - __flaky__
    continue-on-error: true
    # env:
    #   CACHE_PATH: /tmp/.buildx-cache
    #   CACHE_KEY: qfc-test-docker-${{ github.sha }}
    #   CACHE_RESTORE_KEY: qfc-test-docker-
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Check env vars configuration
        run: |
          scripts/check_envvars.sh

      - name: Export the env variables file
        run: |
          cp .env.example .env
          sed -ri 's/^COMPOSE_FILE=(.*)/COMPOSE_FILE=\1:docker-compose.override.test.yml/g' .env
          eval $(egrep "^[^#;]" .env | xargs -d'\n' -n1 | sed -E 's/(\w+)=(.*)/export \1='"'"'\2'"'"'/g')

      - name: Pull docker containers
        run: docker compose pull

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      # - name: Load cache from GitHub Actions cache
      #   uses: actions/cache@v3
      #   with:
      #     path: $CACHE_PATH
      #     key: $CACHE_KEY
      #     restore-keys: $CACHE_RESTORE_KEY

      # - name: Build compose stack
      #   run: docker buildx bake -f docker-compose-cache.json

      - name: Create local cache folders
        run: |
          mkdir -p /tmp/.buildx-cache
          mkdir -p /tmp/.buildx-cache-new

      - name: Build images
        uses: docker/bake-action@v5
        with:
          push: false
          load: true
          set: |
              *.cache-from=type=local,src=/tmp/.buildx-cache
              *.cache-to=type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Run docker containers
        run: |
          docker compose up -d

      - name: Initial manage.py commands
        run: |
          docker compose run app python manage.py makemigrations --no-input --check
          docker compose run app python manage.py migrate
          docker compose run app python manage.py collectstatic

      - name: Run mandatory unit and integration tests
        if: matrix.django_app != '__flaky__'
        run: |
          docker compose run app python manage.py test --keepdb -v2 --exclude-tag="flaky" qfieldcloud.${{ matrix.django_app }}

      - name: Run flaky unit and integration tests
        if: matrix.django_app == '__flaky__'
        run: |
          docker compose run app python manage.py test --keepdb -v2 --tag="flaky" qfieldcloud

      - name: "failure logs"
        if: failure()
        run: |
          docker compose logs

      # - name: Save cache to GitHub Actions cache
      #   uses: actions/cache@v3
      #   with:
      #     path: $CACHE_PATH
      #     key: $CACHE_KEY

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Post Google Chat message on failure
        if: failure() && matrix.django_app != '__flaky__'
        uses: julb/action-post-googlechat-message@v1
        with:
          message: |
            Failed job run for branch `${{ github.head_ref || github.ref_name }}`, check ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} .
          gchat_webhook_url: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}

      # - name: Setup tmate session
      #   if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v3
      #   timeout-minutes: 30
      #   with:
      #     limit-access-to-actor: true
